name: $(date:yyyymmdd)$(rev:.rr) #20191209.xx

trigger:
   - master

stages:
   - stage: compile
     jobs:
         - job: aspnet
           pool:
               vmImage: ubuntu-18.04
           steps:
               - script: |
                 dotnet build 3_devops/Devops.sln
